# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Daniel Ortíz Montero
title: Electrical Engineering, Systems Engineering
email: luis.ortiz7@utp.ac.pa
website: www.github.com/luisortiz11

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  luisortiz11
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: LuisDannielxD
# flickr_username: jekyll
instagram_username: l001s.rt33z
linkedin_username: luis-ortíz-bd1102
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there! My name's Luis and I'm an electrical and systems engineering student. 
  In addition to working with electrical equipment and administrating networks, 
  I also have experience making software, web apps, solving problems and CAD designing. 
  I enjoy solving problems, especially if they require some clever approach that I've never learned before. 
  This means that I'm better suited for back-end development and managing databases, but I can do front-end, UI/UX as well.
  
  

content:
  - title: Best Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Appointment website for a dentist.
        link: https://github.com/luisortiz11/prog4-uip-proyectofinal
        # link_text: Project Website
        additional_links:
          - title:  luisortiz11
            icon: fab fa-github
            url: github.com/luisortiz11/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Feel free to visit my Github repositories.
        description: | # this will include new lines to allow paragraphs
          I deployed this web app using Heroku. The backend is based on Python and Flask with a MongoDB database. The best feature
          of this project is the automatic e-mailing to both parties regarding the appointments. I also added threading to the code,
          so that the emailing task doesn´t make the website feel sluggish. The code could be rewritten to focus on asynchronous tasks to have a
          better control on the timing, specially if the software requires scaling. 

 
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in electrical engineering, networks, and software engineering some of my other interests and hobbies are:
      - Weightlifting
      - Basketball
      - Volleyball
      - Running
      - Hiking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
